// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4IAQmQ-AEoV_PTTrYd-f7sbgyZRg91Vw',
    appId: '1:240236840777:web:1caa68ceb8e8f1a3a07c98',
    messagingSenderId: '240236840777',
    projectId: 'bookswap-ae85c',
    authDomain: 'bookswap-ae85c.firebaseapp.com',
    storageBucket: 'bookswap-ae85c.firebasestorage.app',
    measurementId: 'G-09PX9YDCE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaG3QgMR4nLx7JId69-3SU4RsFs2hTLy4',
    appId: '1:240236840777:android:bac3e5471401e313a07c98',
    messagingSenderId: '240236840777',
    projectId: 'bookswap-ae85c',
    storageBucket: 'bookswap-ae85c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACANdQJ1vWpclHRXTQ024XrGkFoxi0Ax0',
    appId: '1:240236840777:ios:47e1514d6b7fdde1a07c98',
    messagingSenderId: '240236840777',
    projectId: 'bookswap-ae85c',
    storageBucket: 'bookswap-ae85c.firebasestorage.app',
    iosClientId: '240236840777-hbrc7l4v0v2e3arqm3agjjt8ot53pehc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACANdQJ1vWpclHRXTQ024XrGkFoxi0Ax0',
    appId: '1:240236840777:ios:47e1514d6b7fdde1a07c98',
    messagingSenderId: '240236840777',
    projectId: 'bookswap-ae85c',
    storageBucket: 'bookswap-ae85c.firebasestorage.app',
    iosClientId: '240236840777-hbrc7l4v0v2e3arqm3agjjt8ot53pehc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4IAQmQ-AEoV_PTTrYd-f7sbgyZRg91Vw',
    appId: '1:240236840777:web:c8e78be7147f69baa07c98',
    messagingSenderId: '240236840777',
    projectId: 'bookswap-ae85c',
    authDomain: 'bookswap-ae85c.firebaseapp.com',
    storageBucket: 'bookswap-ae85c.firebasestorage.app',
    measurementId: 'G-GV4J903Y92',
  );

}