import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI (optional)
import 'package:firebase_app_check/firebase_app_check.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.debug, // change for production
      // webRecaptchaSiteKey: 'REPLACE_WITH_WEB_KEY_IF_WEB_ONLY',
    );
  } catch (e) {
    // Handle initialization error silently
  }
  runApp(const MyApp());
}
